    # this database is only available on localhost, 
    # so passwords are unnecessary and can be checked in in clear text.
    database: 
      host: localhost
      username: user
      password: password
      database: db
    port: 8080
    